### GET request to get all patients
GET http://localhost:4000/patients

###

### GET request to get all patients
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "matty Qel",
  "email": "aeon@gmail.com",
  "address": "125, Broad street, estate.",
  "dateOfBirth": "1991-09-09",
  "registeredDate": "2025-11-11"
}

###